version: '3.3'

services:
  db:
    image: mysql:5.7
    volumes:
      - ./volumes/mysql:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
  wordpress:
    depends_on:
      - db
    image: wordpress:5.4.0-php7.2-fpm-alpine
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
    volumes:
      - ./volumes/wordpress:/var/www/html
      - ./config/php/php-uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
  nginx:
    image: nginx:1.17.10-alpine
    depends_on:
      - db
    ports:
      - '80:80'
    volumes:
      - ./config/nginx:/etc/nginx/conf.d
      - ./logs:/var/log/nginx
      - ./volumes/wordpress:/var/www/html
    restart: always
